### ISSUE TITLE
请问docker版本还在用吗？是否有简易文档？

### ISSUE THREAD

**Issue by lululutx** [puzzlemoondev/biliup-rs-docker#1]
从dockerhub拉下来的无限重启。
请问文件夹映射什么？端口映射什么？环境是否需要特殊配置？

**Comment by puzzlemoondev** [comment]
這個主要是拿來build各種architecture的biliup-rs
要直接用就是用run的，請看readme的用法
用在Dockerfile的COPY是沒問題的，現在我也還在用
